@startuml
hide circle
skinparam classAttributeIconSize 0

class App 
class ProfilePage
class ProfileTabs
class FriendList
class Pet
class AddPet
class SettingsPage
class PostsContainer
class Playgroups
class PlaygroupForm
class PlaygroupInfo
class Shop
class Post
class SubmitComment
class SubmitPost
class AccountSettings
class NotificationsSettings
class PrivacySettings
class Chat
class Login
class ResetPassword
class Signup
class TopBar
class SideBar
class RightNotificationBar
class RightChatBar
class Notifications

App -->"1" Login
App -->"1" Signup
App -->"1" ResetPassword
App -->"1" PostsContainer
App -->"1" ProfilePage
App -->"1" SettingsPage
App -->"1" Playgroups
App -->"1" Shop
ProfilePage --> "1" ProfileTabs
ProfilePage --> "1" FriendList
ProfilePage --> "1" Pet
ProfilePage --> "1" AddPet
ProfileTabs --> "1" Post
Playgroups --> "1" PlaygroupForm
Playgroups --> "1" PlaygroupInfo
SettingsPage --> "1" AccountSettings
SettingsPage --> "1" NotificationsSettings
SettingsPage --> "1" PrivacySettings
PostsContainer --> "1" SubmitPost
PostsContainer --> "0...*" Post
Post --> "0...*" Comment
Post --> "0...1" SubmitComment
TopBar --> "1" SideBar
TopBar --> "1" RightNotificationBar
TopBar --> "1" RightChatBar
TopBar --> "1" Notifications
RightChatBar --> "0...*" Chat
App --> "1" TopBar
@enduml